msgid ""
msgstr ""
"Project-Id-Version: duplicity\n"
"Report-Msgid-Bugs-To: Kenneth Loafman <kenneth@loafman.com>\n"
"POT-Creation-Date: 2024-11-17 10:47-0600\n"
"PO-Revision-Date: 2024-11-17 17:08\n"
"Last-Translator: \n"
"Language-Team: Japanese\n"
"Language: ja_JP\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Crowdin-Project: duplicity\n"
"X-Crowdin-Project-ID: 539508\n"
"X-Crowdin-Language: ja\n"
"X-Crowdin-File: /main/po/duplicity.pot\n"
"X-Crowdin-File-ID: 6\n"

#: ../duplicity/__main__.py:76
msgid "INT intercepted...exiting."
msgstr "INTが傍受しました...終了します。"

#: ../duplicity/__main__.py:84
#, python-format
msgid "GPG error detail: %s"
msgstr "GPG エラーの詳細: %s"

#: ../duplicity/__main__.py:91
#, python-format
msgid "User error detail: %s"
msgstr "ユーザーエラーの詳細: %s"

#: ../duplicity/__main__.py:98
#, python-format
msgid "Backend error detail: %s"
msgstr "バックエンドエラーの詳細: %s"

#: ../duplicity/argparse311.py:291
msgid "usage: "
msgstr "使用方法: "

#: ../duplicity/argparse311.py:761
#, python-format
msgid "argument %(argument_name)s: %(message)s"
msgstr "引数 %(argument_name)s: %(message)s"

#: ../duplicity/argparse311.py:870
msgid ".__call__() not defined"
msgstr "__call__() が定義されていません"

#: ../duplicity/argparse311.py:1115
#, python-format
msgid "conflicting subparser: %s"
msgstr "競合するサブパーサ: %s"

#: ../duplicity/argparse311.py:1118
#, python-format
msgid "conflicting subparser alias: %s"
msgstr "conflicting subparser alias: %s"

#: ../duplicity/argparse311.py:1152
#, python-format
msgid "unknown parser %(parser_name)r (choices: %(choices)s)"
msgstr "不明なパーサ %(parser_name)r (選択肢: %(choices)s)"

#: ../duplicity/argparse311.py:1215
#, python-format
msgid "argument \"-\" with mode %r"
msgstr "引数 \"-\" モードは %r"

#: ../duplicity/argparse311.py:1223
#, python-format
msgid "can't open '%(filename)s': %(error)s"
msgstr "開くことができません '%(filename)s': %(error)s"

#: ../duplicity/argparse311.py:1427
#, python-format
msgid "cannot merge actions - two groups are named %r"
msgstr "アクションをマージできません - 2つのグループが %r"

#: ../duplicity/argparse311.py:1462
msgid "'required' is an invalid argument for positionals"
msgstr "'required' はポジショニングに対する無効な引数です"

#: ../duplicity/argparse311.py:1483
#, python-format
msgid "invalid option string %(option)r: must start with a character %(prefix_chars)r"
msgstr "不正なオプション文字列 %(option)r: 文字 %(prefix_chars)r で始まる必要があります"

#: ../duplicity/argparse311.py:1500
#, python-format
msgid "dest= is required for options like %r"
msgstr "%r のようなオプションにはdest= が必要です"

#: ../duplicity/argparse311.py:1517
#, python-format
msgid "invalid conflict_resolution value: %r"
msgstr "不正な競合解決値: %r"

#: ../duplicity/argparse311.py:1534
#, python-format
msgid "conflicting option string: %s"
msgid_plural "conflicting option strings: %s"
msgstr[0] "競合するオプション文字列: %s"

#: ../duplicity/argparse311.py:1595
msgid "mutually exclusive arguments must be optional"
msgstr "互いに排他的な引数は省略可能でなければなりません"

#: ../duplicity/argparse311.py:1670
msgid "positional arguments"
msgstr "位置引数"

#. Used in usage help. (Should be consistent with the "Options:"
#. header.) Example:
#. duplicity [full|incremental] [options] source_path target_url
#: ../duplicity/argparse311.py:1671 ../duplicity/cli_data.py:364
#: ../duplicity/cli_data.py:529 ../duplicity/cli_data.py:583
#: ../duplicity/cli_data.py:718 ../duplicity/cli_data.py:918
msgid "options"
msgstr "オプション"

#: ../duplicity/argparse311.py:1689
msgid "show this help message and exit"
msgstr "このヘルプメッセージを表示して終了します"

#: ../duplicity/argparse311.py:1721
msgid "cannot have multiple subparser arguments"
msgstr "複数のサブパーサ引数を持つことはできません"

#: ../duplicity/argparse311.py:1769 ../duplicity/argparse311.py:2264
#, python-format
msgid "unrecognized arguments: %s"
msgstr "認識できない引数: %s"

#: ../duplicity/argparse311.py:1868
#, python-format
msgid "not allowed with argument %s"
msgstr "%s 引数では許可されていません"

#: ../duplicity/argparse311.py:1912 ../duplicity/argparse311.py:1926
#, python-format
msgid "ignored explicit argument %r"
msgstr "明示的引数を無視しました %r"

#: ../duplicity/argparse311.py:2030
#, python-format
msgid "the following arguments are required: %s"
msgstr "次の引数が必要です: %s"

#: ../duplicity/argparse311.py:2042
#, python-format
msgid "one of the arguments %s is required"
msgstr "引数 %s が必要です"

#: ../duplicity/argparse311.py:2083
msgid "expected one argument"
msgstr "想定された引数は"

#: ../duplicity/argparse311.py:2084
msgid "expected at most one argument"
msgstr "予想されるのは最大1つの議論で"

#: ../duplicity/argparse311.py:2085
msgid "expected at least one argument"
msgstr "少なくとも1つの引数が必要です"

#: ../duplicity/argparse311.py:2089
#, python-format
msgid "expected %s argument"
msgid_plural "expected %s arguments"
msgstr[0] "想定された %s 引数"

#: ../duplicity/argparse311.py:2143
#, python-format
msgid "ambiguous option: %(option)s could match %(matches)s"
msgstr "曖昧なオプション： %(option)s は %(matches)s と一致する可能性があります"

#: ../duplicity/argparse311.py:2207
#, python-format
msgid "unexpected option string: %s"
msgstr "想定外のオプション文字列: %s"

#: ../duplicity/argparse311.py:2402
#, python-format
msgid "%r is not callable"
msgstr "%r は呼び出しできません"

#: ../duplicity/argparse311.py:2419
#, python-format
msgid "invalid %(type)s value: %(value)r"
msgstr "無効な %(type)s 値: %(value)r"

#: ../duplicity/argparse311.py:2429
#, python-format
msgid "invalid choice: %(value)r (choose from %(choices)s)"
msgstr "不正な選択: %(value)r ( %(choices)s から選択)"

#: ../duplicity/argparse311.py:2505
#, python-format
msgid "%(prog)s: error: %(message)s\n"
msgstr "%(prog)s: エラー: %(message)s\n"

#: ../duplicity/backend.py:95
#, python-brace-format
msgid "Import of {imp} Failed"
msgstr ""

#: ../duplicity/backend.py:200
#, python-format
msgid "Could not initialize backend: %s"
msgstr "バックエンドを初期化できませんでした: %s"

#: ../duplicity/backend.py:391
#, python-format
msgid "Backtrace of previous error: %s"
msgstr "以前のエラーのバックトレース: %s"

#: ../duplicity/backend.py:412
#, python-format
msgid "Giving up after %s attempts. %s: %s. (for trace back: set log level DEBUG)"
msgstr ""

#: ../duplicity/backend.py:421
#, python-format
msgid "Giving up after %s attempts. %s: %s"
msgstr "%s の試行後に諦めます。 %s: %s"

#: ../duplicity/backend.py:427
#, python-format
msgid "Attempt of %s Nr. %s failed. %s: %s"
msgstr "%s Nr. %s の試行に失敗しました。 %s: %s"

#: ../duplicity/backend.py:526
#, python-format
msgid "Reading results of '%s'"
msgstr "'%s' の結果を読み込み中"

#: ../duplicity/backend.py:553
#, python-format
msgid "Writing %s"
msgstr "%s を書く"

#: ../duplicity/backend.py:608
#, python-format
msgid "File %s not found locally after get from backend"
msgstr "ファイル %s はバックエンドから取得した後ローカルに見つかりません"

#: ../duplicity/backend.py:661
#, python-format
msgid "%s Remote filesize %d for %s does not match local size %d"
msgstr ""

#: ../duplicity/backends/_testbackend.py:219
#, python-format
msgid "Unexpected exception while validate %s."
msgstr ""

#: ../duplicity/backends/giobackend.py:108
#, python-format
msgid "Connection failed, please check your password: %s"
msgstr "接続に失敗しました。パスワードを確認してください： %s"

#: ../duplicity/backends/multibackend.py:100
#, python-format
msgid "MultiBackend: Could not parse query string %s: %s "
msgstr "MultiBackend: クエリ文字列 %sを解析できませんでした: %s "

#: ../duplicity/backends/multibackend.py:110
#, python-format
msgid "MultiBackend: Invalid query string %s: more than one value for %s"
msgstr "マルチバックエンド: 無効なクエリ文字列 %s: %s の値が複数あります"

#: ../duplicity/backends/multibackend.py:116
#, python-format
msgid "MultiBackend: Invalid query string %s: unknown parameter %s"
msgstr "マルチバックエンド: 無効なクエリ文字列 %s: 不明なパラメータ %s"

#: ../duplicity/backends/multibackend.py:167
#: ../duplicity/backends/multibackend.py:174
#, python-format
msgid "MultiBackend: illegal value for %s: %s"
msgstr "マルチバックエンド: %sの不正な値: %s"

#: ../duplicity/backends/multibackend.py:186
#, python-format
msgid "MultiBackend: Url %s"
msgstr "マルチバックエンド: Url %s"

#: ../duplicity/backends/multibackend.py:189
#, python-format
msgid "MultiBackend: Could not load config file %s: %s "
msgstr "マルチバックエンド: 設定ファイル %sを読み込めませんでした: %s "

#: ../duplicity/backends/multibackend.py:196
#, python-format
msgid "MultiBackend: use store %s"
msgstr "マルチバックエンド: ストア %sを使用"

#: ../duplicity/backends/multibackend.py:200
#, python-format
msgid "MultiBackend: set env %s = %s"
msgstr "マルチバックエンド: env %s = %s を設定"

#: ../duplicity/backends/multibackend.py:214
#, python-format
msgid "Multibackend: register affinity for prefix %s"
msgstr "マルチバックエンド: 接頭辞 %sの親和性を登録する"

#: ../duplicity/backends/multibackend.py:257
#, python-format
msgid "MultiBackend: _put: write to store #%s (%s)"
msgstr "マルチバックエンド: _put: ストアへの書き込み #%s (%s)"

#: ../duplicity/backends/multibackend.py:272
#, python-format
msgid "MultiBackend: failed to write to store #%s (%s), try #%s, Exception: %s"
msgstr "MultiBackend: failed to store #%s (%s), try #%s, exception: %s"

#: ../duplicity/backends/multibackend.py:286
#, python-format
msgid "MultiBackend: failed to write %s. Aborting process."
msgstr "マルチバックエンド: %sの書き込みに失敗しました。プロセスを中止しています。"

#: ../duplicity/backends/multibackend.py:294
#, python-format
msgid "MultiBackend: failed to write %s. Tried all backing stores and none succeeded"
msgstr "マルチバックエンド: %sの書き込みに失敗しました。すべてのバッキングストアを試してみて、どれも成功しませんでした"

#: ../duplicity/backends/multibackend.py:315
#, python-format
msgid "MultiBackend: failed to get %s to %s from %s"
msgstr "マルチバックエンド： %s から %s への %sの取得に失敗しました"

#: ../duplicity/backends/multibackend.py:320
#, python-format
msgid "MultiBackend: failed to get %s. Tried all backing stores and none succeeded"
msgstr "マルチバックエンド: %sの取得に失敗しました。すべてのバッキングストアを試行し、成功しませんでした"

#: ../duplicity/backends/multibackend.py:330
#, python-format
msgid "MultiBackend: %s: %d files"
msgstr "マルチバックエンド: %s: %d ファイル"

#: ../duplicity/backends/multibackend.py:334
msgid "Exception during list of {s.backend.parsed_url.strip_auth()}: "
msgstr "{s.backend.parsed_url.strip_auth()}のリスト中の例外: "

#: ../duplicity/backends/multibackend.py:342
#, python-format
msgid "MultiBackend: combined list: %s"
msgstr "MultiBackend: combined list: %s"

#: ../duplicity/backends/multibackend.py:371
#: ../duplicity/backends/multibackend.py:398
#, python-format
msgid "MultiBackend: failed to delete %s. Tried all backing stores and none succeeded"
msgstr "マルチバックエンド: %sの削除に失敗しました。すべてのバッキングストアを試してみましたが、成功しませんでした。"

#: ../duplicity/backends/onedrivebackend.py:88
#, python-format
msgid "Attempt of initialize_oauth2_session Nr. %s failed. %s: %s"
msgstr "初期化の試行に失敗しました。 %s : %s: %s"

#: ../duplicity/backends/pydrivebackend.py:203
#, python-format
msgid "PyDrive backend: multiple files called '%s'."
msgstr "PyDrive バックエンド: 複数のファイルが '%s' と呼ばれています。"

#: ../duplicity/backends/webdavbackend.py:67
msgid "Missing socket or ssl python modules."
msgstr "ソケットまたは ssl python モジュールがありません。"

#: ../duplicity/backends/webdavbackend.py:87
#, python-format
msgid "Cacert database file '%s' is not readable."
msgstr "Cacert データベース ファイル '%s' は読み取りできません。"

#: ../duplicity/backends/webdavbackend.py:152
#, python-format
msgid "Using WebDAV host %s port %s"
msgstr "WebDAV ホスト %s ポート %s の使用"

#: ../duplicity/backends/webdavbackend.py:153
#, python-format
msgid "Using WebDAV directory %s"
msgstr "Using WebDAV directory %s"

#: ../duplicity/backends/webdavbackend.py:183
#, python-format
msgid "WebDAV create connection on '%s'"
msgstr "WebDAV create connection on '%s'"

#: ../duplicity/backends/webdavbackend.py:191
#, python-format
msgid "WebDAV Unknown URI scheme: %s"
msgstr "WebDAV 不明な URI スキーム: %s"

#: ../duplicity/backends/webdavbackend.py:210
#, python-format
msgid "WebDAV %s %s request with headers: %s "
msgstr "ヘッダー付きWebDAV %s %s リクエスト: %s "

#: ../duplicity/backends/webdavbackend.py:211
#: ../duplicity/backends/webdavbackend.py:234
#, python-format
msgid "WebDAV data length: %s "
msgstr "WebDAV データ長: %s "

#: ../duplicity/backends/webdavbackend.py:214
#, python-format
msgid "WebDAV response status %s with reason '%s'."
msgstr "WebDAV レスポンスステータスが %s 理由は '%s' です。"

#: ../duplicity/backends/webdavbackend.py:220
#, python-format
msgid "WebDAV redirect to: %s "
msgstr "WebDAV リダイレクト : %s "

#: ../duplicity/backends/webdavbackend.py:222
msgid "WebDAV redirected 10 times. Giving up."
msgstr "WebDAVは10回リダイレクトしました。諦めています。"

#: ../duplicity/backends/webdavbackend.py:227
msgid "WebDAV missing location header in redirect response."
msgstr "リダイレクト応答のWebDAV位置ヘッダーが見つかりません。"

#: ../duplicity/backends/webdavbackend.py:232
msgid "WebDAV retry request with authentification headers."
msgstr "認証ヘッダ付きの WebDAV リトライリクエスト。"

#: ../duplicity/backends/webdavbackend.py:233
#, python-format
msgid "WebDAV %s %s request2 with headers: %s "
msgstr "WebDAV %s %s リクエスト2 とヘッダー: %s "

#: ../duplicity/backends/webdavbackend.py:237
#, python-format
msgid "WebDAV response2 status %s with reason '%s'."
msgstr "WebDAV response2 status %s with reason '%s'."

#: ../duplicity/backends/webdavbackend.py:256
msgid "python-kerberos needed to use kerberos                           authorization, falling back to basic auth."
msgstr "python-kerberosはカーベロスの認証を使う必要があり、基本的なオースに戻りました。"

#: ../duplicity/backends/webdavbackend.py:264
#, python-format
msgid "Kerberos authorization failed: %s.                          Falling back to basic auth."
msgstr "Kerberos 認証に失敗しました: %s. ベーシックオースにフォールバックします。"

#: ../duplicity/backends/webdavbackend.py:365
#, python-format
msgid "Creating missing directory %s"
msgstr "ディレクトリ %sを作成していません"

#: ../duplicity/backends/webdavbackend.py:369
#, python-format
msgid "WebDAV MKCOL %s failed: %s %s"
msgstr "WebDAV MKCOL %s に失敗しました: %s %s"

#: ../duplicity/backends/webdavbackend.py:381
#, python-format
msgid "WebDAV path decoding and translation: %s -> %s"
msgstr "WebDAV パスのデコードと翻訳: %s -> %s"

#: ../duplicity/backends/webdavbackend.py:417
#, python-format
msgid "WebDAV GET Bad status code %s reason %s."
msgstr "WebDAV GET 不正なステータスコード %s 理由 %s."

#: ../duplicity/backends/webdavbackend.py:438
#, python-format
msgid "WebDAV PUT Bad status code %s reason %s."
msgstr "WebDAV PUT 不正なステータスコード %s 理由 %s."

#: ../duplicity/backends/webdavbackend.py:457
#, python-format
msgid "WebDAV DEL Bad status code %s reason %s."
msgstr "WebDAV DEL Bad status code %s reason %s."

#. Used in usage help to represent a Unix-style path name. Example:
#. --archive-dir <path>
#: ../duplicity/cli_data.py:103 ../duplicity/cli_data.py:173
#: ../duplicity/cli_data.py:207 ../duplicity/cli_data.py:255
#: ../duplicity/cli_data.py:358 ../duplicity/cli_data.py:381
#: ../duplicity/cli_data.py:552 ../duplicity/cli_data.py:744
#: ../duplicity/cli_data.py:927
msgid "path"
msgstr "小道"

#: ../duplicity/cli_data.py:116
msgid "Hot|Cool|Archive"
msgstr "ホット|クール|アーカイブ"

#. Used in usage help to represent a desired number of
#. something. Example:
#. --num-retries <number>
#: ../duplicity/cli_data.py:121 ../duplicity/cli_data.py:127
#: ../duplicity/cli_data.py:135 ../duplicity/cli_data.py:163
#: ../duplicity/cli_data.py:179 ../duplicity/cli_data.py:451
#: ../duplicity/cli_data.py:471 ../duplicity/cli_data.py:518
#: ../duplicity/cli_data.py:540 ../duplicity/cli_data.py:546
#: ../duplicity/cli_data.py:564 ../duplicity/cli_data.py:635
#: ../duplicity/cli_data.py:643 ../duplicity/cli_data.py:695
#: ../duplicity/cli_data.py:781 ../duplicity/cli_data.py:914
msgid "number"
msgstr "数値"

#. Used in usage help. Example:
#. --timeout <seconds>
#: ../duplicity/cli_data.py:147 ../duplicity/cli_data.py:751
#: ../duplicity/cli_data.py:940
msgid "seconds"
msgstr "秒"

#. Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#: ../duplicity/cli_data.py:195 ../duplicity/cli_data.py:201
#: ../duplicity/cli_data.py:375 ../duplicity/cli_data.py:702
#: ../duplicity/cli_data.py:906
msgid "gpg-key-id"
msgstr "gpg-key-id"

#. Used in usage help to represent a "glob" style pattern for
#. matching one or more files, as described in the documentation.
#. Example:
#. --exclude <shell_pattern>
#: ../duplicity/cli_data.py:212 ../duplicity/cli_data.py:403
#: ../duplicity/cli_data.py:945
msgid "shell_pattern"
msgstr "shell_pattern"

#. Used in usage help to represent the name of a file. Example:
#. --log-file <filename>
#: ../duplicity/cli_data.py:224 ../duplicity/cli_data.py:230
#: ../duplicity/cli_data.py:291 ../duplicity/cli_data.py:409
#: ../duplicity/cli_data.py:903
msgid "filename"
msgstr "ファイル名"

#. Used in usage help to represent a time spec for a previous
#. point in time, as described in the documentation. Example:
#. duplicity remove-older-than time [options] target_url
#: ../duplicity/cli_data.py:236 ../duplicity/cli_data.py:577
#: ../duplicity/cli_data.py:971
msgid "time"
msgstr "時間"

#: ../duplicity/cli_data.py:249 ../duplicity/cli_data.py:415
msgid "regex"
msgstr "Regex"

#: ../duplicity/cli_data.py:352
msgid "interval"
msgstr "間隔"

#: ../duplicity/cli_data.py:398
msgid "imap_mailbox"
msgstr "imap_mailbox"

#: ../duplicity/cli_data.py:423
msgid "If set, an extra file with statistics in json format will be stored with each backup. It includes the statistics printed out on stdout by default. With 'collection-status' it returs these stats."
msgstr "設定すると、json形式の統計情報を持つ追加ファイルが各バックアップとともに保存されます。 デフォルトでは、stdout に出力された統計が含まれます。'collection-status' ではこれらの統計が返されます。"

#: ../duplicity/cli_data.py:431
msgid "file_descriptor"
msgstr "ファイル記述子"

#: ../duplicity/cli_data.py:438
msgid "log_filename"
msgstr "log_filename"

#: ../duplicity/cli_data.py:477
msgid "backup name"
msgstr "バックアップ名"

#: ../duplicity/cli_data.py:594
msgid "s3_endpoint_url"
msgstr "s3_endpoint_url"

#: ../duplicity/cli_data.py:662
msgid "s3_kms_key_id"
msgstr "s3_kms_key_id"

#: ../duplicity/cli_data.py:668
msgid "s3_kms_grant"
msgstr "s3_kms_grant"

#: ../duplicity/cli_data.py:674
msgid "s3_region_name"
msgstr "s3_region_name"

#: ../duplicity/cli_data.py:680
msgid "policy"
msgstr "ポリシー"

#. noun
#: ../duplicity/cli_data.py:685 ../duplicity/cli_data.py:690
#: ../duplicity/cli_data.py:892
msgid "command"
msgstr "(Command)"

#: ../duplicity/cli_data.py:730
msgid "pem formatted bundle of certificate authorities"
msgstr "p.m.フォーマットされた証明書当局のバンドル"

#: ../duplicity/cli_data.py:735
msgid "path to a folder with certificate authority files"
msgstr "証明書権限ファイルのあるフォルダへのパス"

#. abbreviation for "character" (noun)
#: ../duplicity/cli_data.py:757 ../duplicity/cli_data.py:890
msgid "char"
msgstr "char|文字"

#: ../duplicity/cli_data.py:770
msgid "verb"
msgstr "動詞（動詞）"

#: ../duplicity/cli_data.py:788
msgid "extra headers for Webdav, like 'Cookie,name=value'"
msgstr "'Cookie,name=value' のような Webdav の追加ヘッダー"

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other_host[:port]//absolute_path
#: ../duplicity/cli_data.py:881
msgid "absolute_path"
msgstr "絶対パス"

#. Used in usage help. Example:
#. tahoe://alias/some_dir
#: ../duplicity/cli_data.py:884
msgid "alias"
msgstr "alias"

#. Used in help to represent a "bucket name" for Amazon Web
#. Services' Simple Storage Service (S3). Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/cli_data.py:888
msgid "bucket_name"
msgstr "Bucket_name"

#. Used in usage help to represent the name of a container in
#. Amazon Web Services' Cloudfront. Example:
#. cf+http://container_name
#: ../duplicity/cli_data.py:896
msgid "container_name"
msgstr "container_name"

#. noun
#: ../duplicity/cli_data.py:898
msgid "count"
msgstr "カウント"

#. Used in usage help to represent the name of a file directory
#: ../duplicity/cli_data.py:900
msgid "directory"
msgstr "ディレクトリ"

#. Used in usage help, e.g. to represent the name of a code
#. module. Example:
#. rsync://user[:password]@other.host[:port]::/module/some_dir
#: ../duplicity/cli_data.py:910
msgid "module"
msgstr "モジュール"

#. Used in usage help to represent an internet hostname. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:921
msgid "other.host"
msgstr "other.host"

#. Used in usage help. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:924
msgid "password"
msgstr "パスワード"

#. Used in usage help to represent a TCP port number. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:930
msgid "port"
msgstr "ポート"

#. Used in usage help. This represents a string to be used as a
#. prefix to names for backup files created by Duplicity. Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/cli_data.py:934
msgid "prefix"
msgstr "接頭辞："

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other.host[:port]/relative_path
#: ../duplicity/cli_data.py:937
msgid "relative_path"
msgstr "相対パス"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. Example:
#. file:///some_dir
#: ../duplicity/cli_data.py:949
msgid "some_dir"
msgstr "some_dir"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory where files will be
#. coming FROM. Example:
#. duplicity [full|incremental] [options] source_path target_url
#: ../duplicity/cli_data.py:954
msgid "source_path"
msgstr "source_path"

#. Used in usage help to represent a URL files will be coming
#. FROM. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/cli_data.py:958
msgid "source_url"
msgstr "ソースURL"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. where files will be
#. going TO. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/cli_data.py:963
msgid "target_dir"
msgstr "target_dir"

#. Used in usage help to represent a URL files will be going TO.
#. Example:
#. duplicity [full|incremental] [options] source_path target_url
#: ../duplicity/cli_data.py:967
msgid "target_url"
msgstr "target_url"

#. Used in usage help to represent a user name (i.e. login).
#. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:975
msgid "user"
msgstr "ユーザー"

#. account id for b2. Example: b2://account_id@bucket/
#: ../duplicity/cli_data.py:977
msgid "account_id"
msgstr "account_id"

#. application_key for b2.
#. Example: b2://account_id:application_key@bucket/
#: ../duplicity/cli_data.py:980
msgid "application_key"
msgstr "application_key"

#. remote name for rclone.
#. Example: rclone://remote:/some_dir
#: ../duplicity/cli_data.py:983 ../duplicity/dup_collections.py:565
msgid "remote"
msgstr "リモート"

#: ../duplicity/cli_data.py:987
msgid "Backends and their URL formats:"
msgstr "バックエンドとそのURL形式："

#: ../duplicity/cli_main.py:151
msgid "No valid action found. Will imply 'backup' because a path source was given and target is a url location."
msgstr "有効なアクションが見つかりませんでした。パスソースが指定され、ターゲットがURLの場所であるため、「backup」を意味します。"

#: ../duplicity/cli_main.py:159
msgid "No valid action found. Will imply 'restore' because url source was given and target is a local path."
msgstr "有効なアクションが見つかりませんでした。URLソースが与えられ、ターゲットがローカルパスであるため、'復元'を意味します。"

#: ../duplicity/cli_main.py:166
#, python-brace-format
msgid "Invalid '{remainder[0]}' action and cannot be implied from the "
msgstr "'{remainder[0]}' アクションが無効で、暗示することはできません "

#: ../duplicity/cli_main.py:266
#, python-brace-format
msgid "GPG binary is {config.gpg_binary}, version {gpg_version}"
msgstr "GPGバイナリは {config.gpg_binary}、バージョン {gpg_version}"

#: ../duplicity/cli_main.py:315
#, python-brace-format
msgid "Using archive dir: {config.archive_dir_path.uc_name}"
msgstr "アーカイブ dir: {config.archive_dir_path.uc_name} を使用する"

#: ../duplicity/cli_main.py:316
#, python-brace-format
msgid "Using backup name: {config.backup_name}"
msgstr "バックアップ名を使用しています: {config.backup_name}"

#: ../duplicity/cli_util.py:45
msgid "Enter 'duplicity --help' for help screen."
msgstr "ヘルプ画面に「duplicity --help」と入力します。"

#: ../duplicity/cli_util.py:127
msgid "Running in 'ignore errors' mode due to --ignore-errors.\n"
"Please reconsider if this was not intended"
msgstr "--ignore-errors のため「無視エラー」モードで実行しています。\n"
"意図していない場合は再度検討してください。"

#: ../duplicity/cli_util.py:170
msgid "'{val}' is not an int: {str(e)}"
msgstr "'{val}' は int: {str(e)}"

#: ../duplicity/cli_util.py:184
#, python-brace-format
msgid "'{val} is not a single character."
msgstr "'{val} は単一文字ではありません。"

#: ../duplicity/cli_util.py:211
#, python-brace-format
msgid "Source should be pathname, not url.  Got '{val}' instead."
msgstr "ソースは url ではなくパス名でなければなりません。代わりに '{val}' が得られました。"

#: ../duplicity/cli_util.py:213
#, python-brace-format
msgid "Argument source_path '{val}' does not exist."
msgstr "引数 source_path '{val}' は存在しません。"

#: ../duplicity/cli_util.py:219
#, python-brace-format
msgid "Source should be url, not directory.  Got '{val}' instead."
msgstr "ソースは url でなければならず、ディレクトリではありません。代わりに '{val}' が得られました。"

#: ../duplicity/cli_util.py:225
#, python-brace-format
msgid "Target should be directory, not url.  Got '{val}' instead."
msgstr "ターゲットは url ではなくディレクトリである必要があります。代わりに '{val}' が得られました。"

#: ../duplicity/cli_util.py:230
msgid "Unable to create target dir '{val}': {str(e)}"
msgstr "ターゲット dir '{val}'を作成できません: {str(e)}"

#: ../duplicity/cli_util.py:236
#, python-brace-format
msgid "Target should be url, not directory.  Got '{val}' instead."
msgstr "ターゲットは URL で、ディレクトリではありません。代わりに '{val}' が得られました。"

#: ../duplicity/cli_util.py:281
msgid "Verbosity must be one of: digit [0-9], character [ewnid],\n"
"or word ['error', 'warning', 'notice', 'info', 'debug'].\n"
"The default is 3 (Notice).  It is strongly recommended\n"
"that verbosity level is set at 2 (Warning) or higher."
msgstr ""

#: ../duplicity/cli_util.py:425
#, python-brace-format
msgid "Specified archive directory '{archive_dir_path.uc_name}' is not a directory"
msgstr "指定されたアーカイブディレクトリ '{archive_dir_path.uc_name}' はディレクトリではありません"

#: ../duplicity/cli_util.py:434
msgid "Encrypt key should be an 8, 16, or 40 character hex string, like 'AA0E73D2'.\n"
msgstr "暗号化キーは、'AA0E73D2'のような8、16、または40文字の16進数でなければなりません。\n"

#: ../duplicity/cli_util.py:454
msgid "Hidden dncrypt key should be an 8, 16, or 40 character hex string, like 'AA0E73D2'.\n"
msgstr "非表示のdncryptキーは、'AA0E73D2'のような8、16、または40文字の16進数でなければなりません。\n"

#: ../duplicity/cli_util.py:468
msgid "Sign key should be an 8, 16, or 40 character hex string, like 'AA0E73D2'.\n"
msgstr "サインキーは、'AA0E73D2'のような8、16、または40文字の16進数でなければなりません。\n"

#: ../duplicity/diffdir.py:105 ../duplicity/diffdir.py:404
#, python-format
msgid "Error %s getting delta for %s"
msgstr "%s の %sのデルタ取得エラー"

#: ../duplicity/diffdir.py:119
#, python-format
msgid "Getting delta of %s and %s"
msgstr "%s と %s のデルタを取得しています"

#: ../duplicity/diffdir.py:163
#, python-format
msgid "A %s"
msgstr "%s"

#: ../duplicity/diffdir.py:171
#, python-format
msgid "M %s"
msgstr "M %s"

#: ../duplicity/diffdir.py:194
#, python-format
msgid "Comparing %s and %s"
msgstr "%s と %s の比較"

#: ../duplicity/diffdir.py:207
#, python-format
msgid "D %s"
msgstr "D %s"

#: ../duplicity/dup_collections.py:200 ../duplicity/dup_collections.py:209
#, python-format
msgid "BackupSet.delete: missing %s"
msgstr "BackupSet.delete: %s がありません"

#: ../duplicity/dup_collections.py:235
msgid "Fatal Error: No manifests found for most recent backup"
msgstr "致命的なエラー：最新のバックアップにマニフェストが見つかりません"

#: ../duplicity/dup_collections.py:248
msgid "Fatal Error: Remote manifest does not match local one.  Either the remote backup set or the local archive directory has been corrupted."
msgstr "致命的なエラー：リモートマニフェストがローカルマニフェストと一致しません。リモートバックアップセットまたはローカルアーカイブディレクトリが破損しています。"

#: ../duplicity/dup_collections.py:256
#, python-format
msgid "Error processing remote manifest (%s): %s"
msgstr "リモートマニフェストの処理中にエラーが発生しました (%s): %s"

#: ../duplicity/dup_collections.py:265
msgid "Fatal Error: Neither remote nor local manifest is readable."
msgstr "致命的なエラー: リモートまたはローカルマニフェストは読み取り可能ではありません。"

#: ../duplicity/dup_collections.py:276
#, python-format
msgid "Processing local manifest %s (%s)"
msgstr "ローカルマニフェスト %s (%s) を処理しています"

#: ../duplicity/dup_collections.py:291
msgid "Error processing remote file ({os.fsdecode(remote_file)}): {util.uexc(message)}"
msgstr "リモートファイル処理中にエラーが発生しました ({os.fsdecode(remote_file)}): {util.uexc(message)}"

#: ../duplicity/dup_collections.py:293
msgid "Processing remote file {os.fsdecode(remote_file)} ({len(remote_file_buffer)})"
msgstr "リモートファイル {os.fsdecode(remote_file)} ({len(remote_file_buffer)}) を処理しています"

#: ../duplicity/dup_collections.py:311
msgid "No Jsonstat file found, return empty."
msgstr ""

#: ../duplicity/dup_collections.py:404
msgid "Preferring Backupset over previous one!"
msgstr "以前のものよりもBackbeastを優先します！"

#: ../duplicity/dup_collections.py:408
#, python-format
msgid "Ignoring incremental Backupset (start_time: %s; needed: %s)"
msgstr "増分バックアップを無視しました (start_time: %s; needed: %s)"

#: ../duplicity/dup_collections.py:417
#, python-format
msgid "Added incremental Backupset (start_time: %s / end_time: %s)"
msgstr "増分バックアップを追加しました (start_time: %s / end_time: %s)"

#: ../duplicity/dup_collections.py:490
msgid "Chain start time: "
msgstr "チェーンの開始時間: "

#: ../duplicity/dup_collections.py:491
msgid "Chain end time: "
msgstr "チェーン終了時間: "

#: ../duplicity/dup_collections.py:492
#, python-format
msgid "Number of contained backup sets: %d"
msgstr "バックアップセットの数: %d"

#: ../duplicity/dup_collections.py:493
#, python-format
msgid "Total number of contained volumes: %d"
msgstr "含まれるボリュームの合計数: %d"

#: ../duplicity/dup_collections.py:494 ../duplicity/dup_collections.py:1301
msgid "Type of backup set:"
msgstr "バックアップの種類:"

#: ../duplicity/dup_collections.py:494 ../duplicity/dup_collections.py:1301
msgid "Time:"
msgstr "時間:"

#: ../duplicity/dup_collections.py:494
msgid "Num volumes:"
msgstr "Num ボリューム:"

#: ../duplicity/dup_collections.py:499 ../duplicity/dup_collections.py:1308
msgid "Full"
msgstr "フル"

#: ../duplicity/dup_collections.py:502 ../duplicity/dup_collections.py:1310
msgid "Incremental"
msgstr "増分"

#: ../duplicity/dup_collections.py:563
msgid "local"
msgstr "ローカル"

#: ../duplicity/dup_collections.py:726
msgid "Collection Status"
msgstr "コレクションステータス"

#: ../duplicity/dup_collections.py:728
#, python-format
msgid "Connecting with backend: %s"
msgstr "バックエンドに接続中: %s"

#: ../duplicity/dup_collections.py:729
#, python-format
msgid "Archive dir: %s"
msgstr "アーカイブディレクトリ： %s"

#: ../duplicity/dup_collections.py:732
#, python-format
msgid "Found %d secondary backup chain(s)."
msgstr "%d 個のセカンダリバックアップチェーンが見つかりました。"

#: ../duplicity/dup_collections.py:734
#, python-format
msgid "Secondary chain %d of %d:"
msgstr "二次チェーン %d %d:"

#: ../duplicity/dup_collections.py:739
msgid "Found primary backup chain with matching signature chain:"
msgstr "署名チェーンに一致するプライマリバックアップチェーンが見つかりました:"

#: ../duplicity/dup_collections.py:742
msgid "No backup chains with active signatures found"
msgstr "アクティブな署名を持つバックアップチェーンが見つかりません"

#: ../duplicity/dup_collections.py:745
#, python-format
msgid "Also found %d backup set(s) not part of any chain,"
msgstr "%d バックアップセットはチェーンの一部ではありません。"

#: ../duplicity/dup_collections.py:746
#, python-format
msgid "and %d incomplete backup set(s)."
msgstr "そして %d バックアップセットが不完全です。"

#. "cleanup" is a hard-coded command, so do not translate it
#: ../duplicity/dup_collections.py:748
msgid "These may be deleted by running duplicity with the \"cleanup\" command."
msgstr "これらは \"cleanup\" コマンドとの重複を実行することで削除することができます。"

#: ../duplicity/dup_collections.py:750
msgid "No orphaned or incomplete backup sets found."
msgstr "孤立または不完全なバックアップセットが見つかりませんでした。"

#: ../duplicity/dup_collections.py:766
#, python-format
msgid "%d file(s) exists on backend"
msgstr "%d ファイルがバックエンドに存在します"

#: ../duplicity/dup_collections.py:770
#, python-format
msgid "%d file(s) exist in cache"
msgstr ""

#: ../duplicity/dup_collections.py:824
msgid "Warning, discarding last backup set, because of missing signature file."
msgstr "警告。署名ファイルがないため、最後のバックアップセットを破棄します。"

#: ../duplicity/dup_collections.py:847
msgid "Warning, found the following local orphaned signature file(s):"
msgstr "警告: 以下のローカル孤立した署名ファイルが見つかりました:"

#: ../duplicity/dup_collections.py:855
msgid "Warning, found the following remote orphaned signature file(s):"
msgstr "警告: 次のリモート孤立したシグネチャ・ファイルが見つかりました:"

#: ../duplicity/dup_collections.py:863
msgid "Warning, found signatures but no corresponding backup files"
msgstr "警告：署名が見つかりましたが、対応するバックアップファイルはありません"

#: ../duplicity/dup_collections.py:869
msgid "Warning, found incomplete backup sets, probably left from aborted session"
msgstr "警告：不完全なバックアップセットが見つかりました、おそらく中断されたセッションから残っています"

#: ../duplicity/dup_collections.py:875
msgid "Warning, found the following orphaned backup file(s):"
msgstr "警告：以下の孤立したバックアップファイルが見つかりました："

#: ../duplicity/dup_collections.py:890
#, python-format
msgid "Extracting backup chains from list of files: %s"
msgstr "ファイルのリストからバックアップチェーンを抽出中: %s"

#: ../duplicity/dup_collections.py:901
#, python-format
msgid "File %s is part of known set"
msgstr "ファイル %s は既知のセットの一部です"

#: ../duplicity/dup_collections.py:904
#, python-format
msgid "File %s is not part of a known set; creating new set"
msgstr "ファイル %s は既知のセットの一部ではありません。新しいセットを作成します"

#: ../duplicity/dup_collections.py:909
#, python-format
msgid "Ignoring file (rejected by backup set) '%s'"
msgstr "無視ファイル (バックアップセットによって拒否されました) '%s'"

#: ../duplicity/dup_collections.py:925
#, python-format
msgid "Found backup chain %s"
msgstr "バックアップチェーン %sが見つかりました"

#: ../duplicity/dup_collections.py:930
#, python-format
msgid "Added set %s to pre-existing chain %s"
msgstr "既存のチェーン %s にセット %sを追加しました"

#: ../duplicity/dup_collections.py:933
#, python-format
msgid "Found orphaned set %s"
msgstr "孤立した集合 %s が見つかりました"

#: ../duplicity/dup_collections.py:1081
#, python-format
msgid "No signature chain for the requested time. Using oldest available chain, starting at time %s."
msgstr "リクエストされた時間に署名チェーンはありません。最も古い使用可能なチェーンを使用しています。 %s から始まります。"

#: ../duplicity/dup_collections.py:1299
#, python-format
msgid "File: %s"
msgstr "ファイル: %s"

#: ../duplicity/dup_collections.py:1300
#, python-format
msgid "Total number of backup: %d"
msgstr "バックアップの総数: %d"

#: ../duplicity/dup_collections.py:1301 ../duplicity/dup_collections.py:1337
msgid "Type of file change:"
msgstr "ファイルの変更の種類:"

#: ../duplicity/dup_collections.py:1335
#, python-format
msgid " Backup set time: %s"
msgstr " バックアップ設定時間： %s"

#: ../duplicity/dup_collections.py:1336
#, python-format
msgid "Total number of changes: %d"
msgstr "合計変更回数: %d"

#: ../duplicity/dup_collections.py:1337
msgid "File:"
msgstr "ファイル:"

#: ../duplicity/dup_main.py:109
msgid "Reuse configured PASSPHRASE as SIGN_PASSPHRASE"
msgstr "SIGN_PASSPHRASE として設定された PASSPHRASE を再利用する"

#: ../duplicity/dup_main.py:120
msgid "Reuse configured SIGN_PASSPHRASE as PASSPHRASE"
msgstr "設定済みの SIGN_PASSPHRASE をPASSPHRASE として再利用する"

#: ../duplicity/dup_main.py:155
msgid "PASSPHRASE variable not set, asking user."
msgstr "PASSPHRASE 変数が設定されていません。"

#: ../duplicity/dup_main.py:180
msgid "Retype passphrase for signing key to confirm: "
msgstr "確認のために署名キーのパスフレーズを再入力してください: "

#: ../duplicity/dup_main.py:182
msgid "Retype passphrase for decryption to confirm: "
msgstr "復号化のためのパスフレーズを再入力してください: "

#: ../duplicity/dup_main.py:186
msgid "First and second passphrases do not match!  Please try again."
msgstr "最初と2番目のパスフレーズが一致しません！もう一度やり直してください。"

#: ../duplicity/dup_main.py:197
msgid "Cannot use empty passphrase with symmetric encryption!  Please try again."
msgstr "対称暗号化で空のパスフレーズは使用できません。もう一度やり直してください。"

#: ../duplicity/dup_main.py:257
#, python-format
msgid "File %s complete in backup set.\n"
"Continuing restart on file %s."
msgstr "ファイル %s はバックアップセットで完了しました。\n"
"ファイル %sで再起動を続けます。"

#: ../duplicity/dup_main.py:267
#, python-format
msgid "File %s missing in backup set.\n"
"Continuing restart on file %s."
msgstr "ファイル %s がバックアップにありません。\n"
"ファイル %sで再起動を続けます。"

#: ../duplicity/dup_main.py:322
#, python-format
msgid "File %s was corrupted during upload."
msgstr "ファイル %s はアップロード中に破損しました。"

#: ../duplicity/dup_main.py:352
msgid "Restarting backup, but current encryption settings do not match original settings"
msgstr "バックアップを再起動していますが、現在の暗号化設定は元の設定と一致しません"

#: ../duplicity/dup_main.py:375 ../duplicity/dup_main.py:511
#, python-format
msgid "Processed volume %d"
msgstr "処理されたボリュームの %d"

#: ../duplicity/dup_main.py:423
msgid "Skipping encryption validation due to glacier/deep storage"
msgstr "氷河/深層ストレージによる暗号化検証のスキップ中"

#: ../duplicity/dup_main.py:427
#, python-format
msgid "Restarting after volume %s, file %s, block %s"
msgstr "ボリューム %s後に再起動、ファイル %s、ブロック %s"

#: ../duplicity/dup_main.py:479
msgid "Skipped volume upload, as effectivly nothing has changed"
msgstr "ボリュームのアップロードをスキップしました。効果的に何も変更されていません。"

#: ../duplicity/dup_main.py:702
msgid "Fatal Error: Unable to start incremental backup.  Old signatures not found and incremental specified"
msgstr "致命的なエラー：増分バックアップを開始できません。古い署名が見つからず、増分が指定されています。"

#: ../duplicity/dup_main.py:708
msgid "No signatures found, switching to full backup."
msgstr "署名が見つかりません。完全バックアップに切り替えています。"

#: ../duplicity/dup_main.py:722
msgid "Backup Statistics"
msgstr "統計情報のバックアップ"

#: ../duplicity/dup_main.py:862
#, python-format
msgid "%s not found in archive - no files restored."
msgstr "%s はアーカイブに見つかりません - 復元されたファイルはありません。"

#: ../duplicity/dup_main.py:866
msgid "No files found in archive - nothing restored."
msgstr "アーカイブにファイルが見つかりませんでした。復元されたファイルはありません。"

#: ../duplicity/dup_main.py:904
#, python-format
msgid "Processed volume %d of %d"
msgstr "処理されたボリューム %d の %d"

#: ../duplicity/dup_main.py:947
#, python-format
msgid "Invalid data - %s hash mismatch for file:"
msgstr "無効なデータ - %s ハッシュがファイルに一致しません:"

#: ../duplicity/dup_main.py:949
#, python-format
msgid "Calculated hash: %s"
msgstr "計算されたハッシュ: %s"

#: ../duplicity/dup_main.py:950
#, python-format
msgid "Manifest hash: %s"
msgstr "マニフェストハッシュ: %s"

#: ../duplicity/dup_main.py:957 ../duplicity/util.py:110
#, python-format
msgid "IGNORED_ERROR: Warning: ignoring error as requested: %s: %s"
msgstr "無視エラー: 警告: 要求されたエラーを無視: %s: %s"

#: ../duplicity/dup_main.py:1004
#, python-format
msgid "Volume was signed by key %s, not %s"
msgstr "ボリュームはキー %sによって署名されました。 %s ではありません。"

#: ../duplicity/dup_main.py:1036
#, python-format
msgid "Verify complete: %s, %s."
msgstr "検証完了: %s, %s."

#: ../duplicity/dup_main.py:1037
#, python-format
msgid "%d file(s) compared"
msgstr "%d ファイルの比較"

#: ../duplicity/dup_main.py:1037
#, python-format
msgid "%d difference(s) found"
msgstr "%d 差分が見つかりました"

#: ../duplicity/dup_main.py:1056
msgid "No extraneous files found, nothing deleted in cleanup."
msgstr "無関係なファイルが見つかりません。クリーンアップで削除されたファイルはありません。"

#: ../duplicity/dup_main.py:1071
msgid "Found the following file(s) to delete:"
msgstr "削除する次のファイルが見つかりました:"

#: ../duplicity/dup_main.py:1075
msgid "Run duplicity again with the --force option to actually delete."
msgstr "実際に削除するには --force オプションを使用して再度重複を実行します。"

#: ../duplicity/dup_main.py:1121
msgid "There are backup set(s) at time(s):"
msgstr "バックアップセットがあります:"

#: ../duplicity/dup_main.py:1123
msgid "Which can't be deleted because newer sets depend on them."
msgstr "新しいセットがそれらに依存しているため、削除できません。"

#: ../duplicity/dup_main.py:1130
msgid "Current active backup chain is older than specified time.  However, it will not be deleted.  To remove all your backups, manually purge the repository."
msgstr "現在のアクティブなバックアップチェーンは指定された時間より古いです。ただし、削除されることはありません。すべてのバックアップを削除するには、リポジトリを手動で削除してください。"

#: ../duplicity/dup_main.py:1148
msgid "No old backup sets found, nothing deleted."
msgstr "古いバックアップセットが見つかりませんでした。削除されたものはありません。"

#: ../duplicity/dup_main.py:1151
msgid "Deleting backup chain(s) at time:"
msgstr "バックアップチェーンを削除:"

#: ../duplicity/dup_main.py:1160
#, python-format
msgid "Deleting any incremental signature chain rooted at %s"
msgstr "%s に根ざした増分署名チェーンを削除する"

#: ../duplicity/dup_main.py:1162
#, python-format
msgid "Deleting any incremental backup chain rooted at %s"
msgstr "%s に根ざした増分バックアップチェーンを削除する"

#: ../duplicity/dup_main.py:1165
#, python-format
msgid "Deleting complete signature chain %s"
msgstr "完全な署名連鎖 %sを削除しています"

#: ../duplicity/dup_main.py:1167
#, python-format
msgid "Deleting complete backup chain %s"
msgstr "%sの完全なバックアップチェーンを削除しています"

#: ../duplicity/dup_main.py:1174
msgid "Found old backup chain(s) at the following time:"
msgstr "以下の時間で古いバックアップチェーンが見つかりました："

#: ../duplicity/dup_main.py:1178
msgid "Rerun command with --force option to actually delete."
msgstr "--force オプションで実際に削除するコマンドを再実行します。"

#: ../duplicity/dup_main.py:1281
#, python-format
msgid "Deleting local %s (not authoritative at backend)."
msgstr "ローカル %s を削除します (バックエンドでは権限がありません)。"

#: ../duplicity/dup_main.py:1285
#, python-format
msgid "Unable to delete %s: %s"
msgstr "%sを削除できません: %s"

#: ../duplicity/dup_main.py:1319 ../duplicity/dup_temp.py:296
#, python-format
msgid "Failed to read %s: %s"
msgstr "%sの読み込みに失敗しました: %s"

#: ../duplicity/dup_main.py:1331
#, python-format
msgid "Copying %s to local cache."
msgstr "%s をローカルキャッシュにコピーしています。"

#: ../duplicity/dup_main.py:1379
msgid "Local and Remote metadata are synchronized, no sync needed."
msgstr "ローカルとリモートのメタデータは同期され、同期は必要ありません。"

#: ../duplicity/dup_main.py:1384
msgid "Synchronizing remote metadata to local cache..."
msgstr "リモートメタデータをローカルキャッシュと同期しています..."

#: ../duplicity/dup_main.py:1398
msgid "Sync would copy the following from remote to local:"
msgstr "同期はリモートからローカルへ以下をコピーします:"

#: ../duplicity/dup_main.py:1404
msgid "Sync would remove the following spurious local files:"
msgstr "同期は次の偽りのローカルファイルを削除します:"

#: ../duplicity/dup_main.py:1450
msgid "Unable to get free space on temp."
msgstr "Tempの空き容量を取得できません。"

#: ../duplicity/dup_main.py:1457
msgid "Temp space has {freespace:,} available, backup needs approx {needspace:,}."
msgstr ""

#: ../duplicity/dup_main.py:1461
msgid "Temp has {freespace:,} available, backup will use approx {needspace:,}."
msgstr ""

#: ../duplicity/dup_main.py:1468
msgid "Unable to get max open files."
msgstr "最大ファイルを開くことができません。"

#: ../duplicity/dup_main.py:1473
#, python-brace-format
msgid "Max open files of {maxopen} is too low, should be >= 1024.\n"
msgstr ""

#: ../duplicity/dup_main.py:1528
msgid "RESTART: The first volume failed to upload before termination.\n"
"         Restart is impossible...starting backup from beginning."
msgstr "最初のボリュームは終了前にアップロードできませんでした。\n"
"         再起動はできません...最初からバックアップを開始してください。"

#: ../duplicity/dup_main.py:1538
#, python-format
msgid "RESTART: Volumes %d to %d failed to upload before termination.\n"
"         Restarting backup at volume %d."
msgstr "RESTART: ボリューム「 %d to %d 」は終了前にアップロードできませんでした。\n"
"         ボリューム「 %d」でバックアップを再開しています。"

#: ../duplicity/dup_main.py:1549
#, python-format
msgid "RESTART: Impossible backup state: manifest has %d vols, remote has %d vols.\n"
"         Restart is impossible ... duplicity will clean off the last partial\n"
"         backup then restart the backup from the beginning."
msgstr ""

#: ../duplicity/dup_main.py:1575
msgid "                PYTHONOPTIMIZE in the environment causes duplicity to fail to\n"
"                recognize its own backups.  Please remove PYTHONOPTIMIZE from\n"
"                the environment and rerun the backup.\n\n"
"                See https://bugs.launchpad.net/duplicity/+bug/931175\n"
"                "
msgstr ""

#: ../duplicity/dup_main.py:1655
#, python-brace-format
msgid "Last {action} backup left a partial set, restarting."
msgstr "前回の {action} バックアップは部分的なセットを残し、再起動しました。"

#: ../duplicity/dup_main.py:1659
#, python-brace-format
msgid "Cleaning up previous partial {action} backup set, restarting."
msgstr "前の部分的な {action} バックアップをクリーンアップしました。再起動します。"

#: ../duplicity/dup_main.py:1673
msgid "Last full backup date: none"
msgstr "最終バックアップ日: なし"

#: ../duplicity/dup_main.py:1680
msgid "Last full backup is too old, forcing full backup"
msgstr "前回のフルバックアップが古すぎるため、完全バックアップが強制されます"

#: ../duplicity/dup_main.py:1736
msgid "When using symmetric encryption, the signing passphrase must equal the encryption passphrase."
msgstr "共通鍵暗号を使用する場合、署名パスフレーズは暗号化パスフレーズと同じでなければなりません。"

#: ../duplicity/dup_time.py:54
#, python-format
msgid "Bad interval string \"%s\"\n\n"
"Intervals are specified like 2Y (2 years) or 2h30m (2.5 hours).  The\n"
"allowed special characters are s, m, h, D, W, M, and Y.  See the man\n"
"page for more information."
msgstr ""

#: ../duplicity/dup_time.py:63
#, python-format
msgid "Bad time string \"%s\"\n\n"
"The acceptible time strings are intervals (like \"3D64s\"), w3-datetime\n"
"strings, like \"2002-04-26T04:22:01-07:00\" (strings like\n"
"\"2002-04-26T04:22:01\" are also acceptable - duplicity will use the\n"
"current time zone), or ordinary dates like 2/4/1997 or 2001-04-23\n"
"(various combinations are acceptable, but the month always precedes\n"
"the day)."
msgstr ""

#: ../duplicity/gpginterface.py:694
#, python-brace-format
msgid "GPG process {process.pid} terminated before wait()"
msgstr "GPGプロセス {process.pid} が wait() の前に終了しました"

#: ../duplicity/lazy.py:349
#, python-format
msgid "Warning: oldindex %s >= newindex %s"
msgstr "警告: 古いインデックス %s >= newindex %s"

#: ../duplicity/lazy.py:424
#, python-format
msgid "Error '%s' processing %s"
msgstr "エラー '%s' processing %s"

#: ../duplicity/lazy.py:436
#, python-format
msgid "Skipping %s because of previous error"
msgstr "以前のエラーのため %s をスキップしています"

#: ../duplicity/librsync.py:194
msgid "basis_file must be a (true) file or an object whose file attribute is the underlying true file object"
msgstr "basis_file は (true) ファイルまたはファイル属性が元の真のファイルオブジェクトであるオブジェクトでなければなりません"

#: ../duplicity/manifest.py:95
#, python-format
msgid "Fatal Error: Backup source host has changed.\n"
"Current hostname: %s\n"
"Previous hostname: %s"
msgstr "致命的なエラー: バックアップソースホストが変更されました。\n"
"現在のホスト名: %s\n"
"前のホスト名: %s"

#: ../duplicity/manifest.py:102
msgid "Fatal Error: Backup source directory has changed.\n"
msgstr "致命的なエラー: バックアップソースディレクトリが変更されました。\n"

#: ../duplicity/manifest.py:115
msgid "Aborting because you may have accidentally tried to backup two different data sets to the same remote location, or using the same archive directory.  If this is not a mistake, use the --allow-source-mismatch switch to avoid seeing this message"
msgstr "誤って2つの異なるデータセットを同じリモートの場所にバックアップしようとしたか、同じアーカイブディレクトリを使用している可能性があるため、中断します。 これが間違いでない場合は、このメッセージが表示されないように--allow-source-mismatch スイッチを使用してください。"

#: ../duplicity/manifest.py:221
#, python-format
msgid "Found manifest volume %s"
msgstr "マニフェスト音量 %sが見つかりました"

#: ../duplicity/manifest.py:228
#, python-format
msgid "Found %s volumes in manifest"
msgstr "マニフェストに %s ボリュームが見つかりました"

#: ../duplicity/manifest.py:249
msgid "Manifest file '{self.fh.base if self.fh else ''}' is corrupt: "
msgstr "マニフェストファイル '{self.fh.base if self.fh else ''}' が破損しています: "

#: ../duplicity/manifest.py:268
msgid "Manifests not equal because different volume numbers"
msgstr "ボリューム番号が異なるためマニフェストは等しくありません"

#: ../duplicity/manifest.py:273
msgid "Manifests not equal because volume lists differ"
msgstr "ボリュームリストが異なるためマニフェストは等しくありません"

#: ../duplicity/manifest.py:277
msgid "Manifests not equal because hosts or directories differ"
msgstr "ホストやディレクトリが異なるためマニフェストは等しくありません"

#: ../duplicity/manifest.py:438
msgid "Warning, found extra Volume identifier"
msgstr "警告、追加のボリューム識別子が見つかりました"

#: ../duplicity/manifest.py:464
msgid "Other is not VolumeInfo"
msgstr "その他はボリューム情報ではありません"

#: ../duplicity/manifest.py:467
msgid "Volume numbers don't match"
msgstr "ボリューム番号が一致しません"

#: ../duplicity/manifest.py:470
msgid "start_indicies don't match"
msgstr "start_indicies が一致しません"

#: ../duplicity/manifest.py:473
msgid "end_index don't match"
msgstr "end_index が一致しません"

#: ../duplicity/manifest.py:478
msgid "Hashes don't match"
msgstr "ハッシュが一致しません"

#: ../duplicity/patchdir.py:73 ../duplicity/patchdir.py:80
#, python-format
msgid "Patching %s"
msgstr "パッチ %s"

#: ../duplicity/patchdir.py:548
#, python-format
msgid "Error '%s' patching %s"
msgstr ""

#: ../duplicity/patchdir.py:625
#, python-format
msgid "Writing %s of type %s"
msgstr "%s タイプの %sを書く"

#: ../duplicity/path.py:109
#, python-format
msgid "Warning: %s invalid devnums (0x%X), treating as (0, 0)."
msgstr "警告: %s invalid devnums (0x%X), treating as (0, 0)."

#: ../duplicity/path.py:239 ../duplicity/path.py:299
#, python-format
msgid "Warning: %s has negative mtime, treating as 0."
msgstr "警告: %s は負の mtime, 0 として扱われます。"

#: ../duplicity/path.py:372
#, python-format
msgid "New file %s"
msgstr "新しいファイル %s"

#: ../duplicity/path.py:375
#, python-format
msgid "File %s is missing"
msgstr "%s ファイルがありません"

#: ../duplicity/path.py:378
#, python-format
msgid "File %%s has type %s, expected %s"
msgstr "ファイル %%s は %s型を持っています, 期待値 %s"

#: ../duplicity/path.py:383 ../duplicity/path.py:412
#, python-format
msgid "File %%s has permissions %s, expected %s"
msgstr ""

#: ../duplicity/path.py:389
#, python-format
msgid "File %%s has mtime %s, expected %s"
msgstr "ファイル %%s は mtime %sを持っています, 期待値 %s"

#: ../duplicity/path.py:400
#, python-format
msgid "Data for file %s is different"
msgstr "ファイル %s のデータが異なります"

#: ../duplicity/path.py:408
#, python-format
msgid "Symlink %%s points to %s, expected %s"
msgstr "シンボリックリンク %%s 点が %s, 期待値 %s"

#: ../duplicity/path.py:415
#, python-format
msgid "Device file %%s has numbers %s, expected %s"
msgstr "デバイス ファイル %%s は番号 %sを持っています, 期待値 %s"

#: ../duplicity/path.py:605
#, python-format
msgid "Making directory %s"
msgstr "ディレクトリを作成しています %s"

#: ../duplicity/path.py:615
#, python-format
msgid "Deleting %s"
msgstr "%s を削除しています"

#: ../duplicity/path.py:624
#, python-format
msgid "Touching %s"
msgstr "%sにタッチ中"

#: ../duplicity/path.py:632
#, python-format
msgid "Deleting tree %s"
msgstr "%s ツリーを削除しています"

#: ../duplicity/robust.py:84
#, python-format
msgid "Error listing directory %s"
msgstr "%s ディレクトリのエラー一覧"

#: ../duplicity/selection.py:115
#, python-format
msgid "Skipping socket %s"
msgstr "ソケット %sをスキップ中"

#: ../duplicity/selection.py:121
#, python-format
msgid "Error initializing file %s"
msgstr "ファイル %sの初期化中にエラーが発生しました"

#: ../duplicity/selection.py:127 ../duplicity/selection.py:167
#: ../duplicity/selection.py:615
#, python-format
msgid "Error accessing possibly locked file %s"
msgstr "ロックされたファイル %sへのアクセスエラー"

#: ../duplicity/selection.py:182
#, python-format
msgid "Warning: base %s doesn't exist, continuing"
msgstr "警告：ベース %s は存在しません、続行します。"

#: ../duplicity/selection.py:184 ../duplicity/selection.py:205
#: ../duplicity/selection.py:208
#, python-format
msgid "Selecting %s"
msgstr "%sを選択中"

#: ../duplicity/selection.py:263
#, python-format
msgid "                The last file selection option is the filter option %s, which will have no\n"
"                effect as there are no subsequent file selection options. Exiting because\n"
"                this probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:278
#, python-format
msgid "                Only these filter mode options were specified:\n"
"                    %s\n"
"                Case sensitive globbing is the default behaviour and so this has no effect.\n"
"                Exiting because this probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:346
#, python-format
msgid "                Fatal Error: The file specification\n"
"                    %s\n"
"                cannot match any files in the base directory\n"
"                    %s\n"
"                Useful file specifications begin with the base directory or some\n"
"                pattern (such as '**') which matches the base directory."
msgstr "                Fatal Error: The file specification\n"
"                    %s\n"
"                cannot match any files in base directory\n"
"                    %s\n"
"                Useful file specifications begin with the base directory or some\n"
"                pattern (such as '**') to match."

#: ../duplicity/selection.py:360
#, python-format
msgid "Fatal Error while processing expression\n"
"%s"
msgstr "式\n"
"%s の処理中に致命的なエラー"

#: ../duplicity/selection.py:378
#, python-format
msgid "Reading files to backup from list %s"
msgstr "リスト %sからバックアップファイルを読み込み中"

#: ../duplicity/selection.py:403
#, python-format
msgid "                Files-from list contains the absolute path:\n"
"                    %s\n"
"                All paths specified in a files-from list must be given relative to the backup\n"
"                source path."
msgstr "                Files-from リストには、絶対パスが含まれています:\n"
"                    %s\n"
"                files-from リストで指定されたすべてのパスは、バックアップ\n"
"                ソースパスからの相対パスを与える必要があります。"

#: ../duplicity/selection.py:418
msgid "                Files-from list specified which contains no files, the backup will be empty as\n"
"                a result. Exiting as this probably isn't what you meant,"
msgstr "                ファイルが含まれていないファイルリストが指定された場合、バックアップは結果として\n"
"                空になります。これはおそらくあなたが意味するものではないため、終了します。"

#: ../duplicity/selection.py:435
#, python-format
msgid "                Last selection expression:\n"
"                    %s\n"
"                only specifies that files be included.  Because the default is to\n"
"                include all files, the expression is redundant.  Exiting because this\n"
"                probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:497
#, python-format
msgid "Reading %s filelist %s"
msgstr "%s ファイルリスト %s を読み込み中"

#: ../duplicity/selection.py:538
#, python-format
msgid "Error compiling regular expression %s"
msgstr "正規表現 %sのコンパイルエラー"

#: ../duplicity/tempdir.py:157
#, python-format
msgid "Using temporary directory %s"
msgstr "一時ディレクトリ %sを使用"

#: ../duplicity/tempdir.py:201
#, python-format
msgid "Registering (mktemp) temporary file %s"
msgstr "登録中(mktemp) 一時ファイル %s"

#: ../duplicity/tempdir.py:227
#, python-format
msgid "Registering (mkstemp) temporary file %s"
msgstr "登録中(mkstemp) 一時ファイル %s"

#: ../duplicity/tempdir.py:259
#, python-format
msgid "Forgetting temporary file %s"
msgstr "一時ファイル %sを忘れています"

#: ../duplicity/tempdir.py:262
#, python-format
msgid "Attempt to forget unknown tempfile %s - this is probably a bug."
msgstr "未知の tempfile %s を忘れようとしています - これはおそらくバグです。"

#: ../duplicity/tempdir.py:281
#, python-format
msgid "Removing still remembered temporary file %s"
msgstr "記憶されている一時ファイル %sを削除しています"

#: ../duplicity/tempdir.py:284
#, python-format
msgid "Cleanup of temporary file %s failed"
msgstr "一時ファイル %s のクリーンアップに失敗しました"

#: ../duplicity/tempdir.py:290
#, python-format
msgid "Cleanup of temporary directory %s failed - this is probably a bug."
msgstr "一時ディレクトリ %s のクリーンアップに失敗しました - これはおそらくバグです。"

#: ../duplicity/util.py:176
#, python-format
msgid "Acquiring lockfile %s"
msgstr "ロックファイル %sを取得中"

#: ../duplicity/util.py:191
#, python-format
msgid "Releasing lockfile %s"
msgstr "ロックファイル %sをリリース"

