class UnexpectedError(Exception):
  pass

class LogicError(Exception):
  pass
